export const moviesData = [
  {
    id: 1,
    title: "The Dark Knight",
    category: "english",
    language: "English",
    year: "2008",
    rating: "9.0",
    duration: "2h 32m",
    image: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=500",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
  },
  {
    id: 2,
    title: "3 Idiots",
    category: "hindi",
    language: "Hindi",
    year: "2009",
    rating: "8.4",
    duration: "2h 50m",
    image: "https://images.unsplash.com/photo-1574267432644-f610f5b7e2e7?w=500",
    description: "Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend.",
  },
  {
    id: 3,
    title: "Inception",
    category: "english",
    language: "English",
    year: "2010",
    rating: "8.8",
    duration: "2h 28m",
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=500",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea.",
  },
  {
    id: 4,
    title: "Avengers: Endgame",
    category: "hindi-dubbed",
    language: "Hindi Dubbed",
    year: "2019",
    rating: "8.4",
    duration: "3h 1m",
    image: "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=500",
    description: "After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos' actions and restore balance.",
  },
  {
    id: 5,
    title: "Dangal",
    category: "hindi",
    language: "Hindi",
    year: "2016",
    rating: "8.3",
    duration: "2h 41m",
    image: "https://images.unsplash.com/photo-1594908900066-3f47337549d8?w=500",
    description: "Former wrestler Mahavir Singh Phogat trains his daughters to become world-class wrestlers.",
  },
  {
    id: 6,
    title: "Interstellar",
    category: "english",
    language: "English",
    year: "2014",
    rating: "8.6",
    duration: "2h 49m",
    image: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=500",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
  },
  {
    id: 7,
    title: "Spider-Man: No Way Home",
    category: "hindi-dubbed",
    language: "Hindi Dubbed",
    year: "2021",
    rating: "8.2",
    duration: "2h 28m",
    image: "https://images.unsplash.com/photo-1635863138275-d9b33299680b?w=500",
    description: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.",
  },
  {
    id: 8,
    title: "Bahubali 2",
    category: "hindi",
    language: "Hindi",
    year: "2017",
    rating: "8.2",
    duration: "2h 47m",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=500",
    description: "When Shiva, the son of Bahubali, learns about his heritage, he begins to look for answers.",
  },
  {
    id: 9,
    title: "The Matrix",
    category: "english",
    language: "English",
    year: "1999",
    rating: "8.7",
    duration: "2h 16m",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=500",
    description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
  },
  {
    id: 10,
    title: "Fast & Furious 9",
    category: "hindi-dubbed",
    language: "Hindi Dubbed",
    year: "2021",
    rating: "5.2",
    duration: "2h 23m",
    image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=500",
    description: "Dom and the crew must take on an international terrorist who turns out to be Dom's forsaken brother.",
  },
  {
    id: 11,
    title: "PK",
    category: "hindi",
    language: "Hindi",
    year: "2014",
    rating: "8.1",
    duration: "2h 33m",
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=500",
    description: "An alien on Earth loses the only device he can use to communicate with his spaceship. His innocent nature and child-like questions force the country to evaluate.",
  },
  {
    id: 12,
    title: "Pulp Fiction",
    category: "english",
    language: "English",
    year: "1994",
    rating: "8.9",
    duration: "2h 34m",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
  },
];
